### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [kuniss/xtext-ide-extensions#7]
Hello Xtext-IDE-Extensions team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Xtext-IDE-Extensions project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by kuniss** [comment]
```
<tr>
	<td><a href="https://github.com/kuniss/xtext-ide-extensions/tree/master/xtext-vscode-extension">VS Code extension for Xtext Language</a></td>
	<td>Xtext Language support for VS code utilizing a Language Server built with Xtext framework itself. Installation via <a href="https://marketplace.visualstudio.com/items?itemName=Grammarcraft.xtend-lang">VS Marketplace</a></td>
	<td>EPL-2.0</td>
	<td>IDE extension</td>
	<td>Denis Kuniß</td>
</tr>
```

**Comment by kuniss** [comment]
Additionally:
```
<tr>
	<td><a href="https://github.com/kuniss/xtext-ide-extensions">TextMate Grammars for the Xtext Language</a></td>
	<td>TextMate grammars for Xtext language highlighting support in different editors, e.g. VS Code, ACE, Atom, Pygments, Rouge, Sublime 3 (except for VS Code, all not tested)</td>
	<td>EPL-2.0</td>
	<td>Editor Support</td>
	<td>Denis Kuniß</td>
</tr>
```

**Comment by miklossy** [comment]
Thank you @kuniss !

**Comment by miklossy** [comment]
The `VS Code extension for Xtext Language` and the `TextMate Grammars for the Xtext Language` projects have been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
